
name: Build APK & Dev Image

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build APK release image
      - name: Build APK Docker image
        run: docker build \
            --build-arg EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest \
            -f Dockerfile .


      - name: Push APK image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest

      # Build Dev image
      - name: Build Dev Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skylance-mobile-dev:latest -f Dockerfile.dev .

      - name: Push Dev image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/skylance-mobile-dev:latest

      # Optional: still upload APK to GitHub artifacts
      - name: Extract APK from image
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest cat /dist/app-release.apk > app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: skylance-apk
          path: app-release.apk