name: Build APK & Dev Image

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build APK release image
      - name: Build APK Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest -f Dockerfile .

      - name: Push APK image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest

      - name: Build & push Dev Docker image (multi-arch)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/skylance-mobile-dev:latest \
            -f Dockerfile.dev \
            --build-arg EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }} \
            --push .

      - name: Extract APK from image
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest cat /dist/app-release.apk > app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: skylance-apk
          path: app-release.apk