name: Build APK with Docker

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_API_URL=${{ secrets.EXPO_PUBLIC_API_URL }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest .

      - name: Push Docker image to registry
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest

      - name: Copy APK from container
        run: |
          container_id=$(docker create ${{ secrets.DOCKERHUB_USERNAME }}/skylance-apk-mobile:latest)
          docker cp $container_id:/app/android/app/build/outputs/apk/release/app-release.apk app-release.apk
          docker rm $container_id

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: skylance-apk
          path: app-release.apk